import Image from "next/image";
import { ArrowDown, ArrowRight, Bird, ChevronDown, Fish, Mail, MapPin, PackageOpen, Phone, Stethoscope } from "lucide-react";
import { branches, proposal } from "@/data/branches";
import { InteractiveShell } from "@/components/InteractiveShell";
import { BranchCards } from "@/components/BranchCards";

const services=[
 {icon:Stethoscope,title:"Atención veterinaria integral",copy:"Un acceso claro para consultar por la atención disponible y comunicarte con la sede que prefieras."},
 {icon:PackageOpen,title:"Alimentos y productos para mascotas",copy:"Una categoría pensada para ordenar opciones de cuidado cotidiano. Consultá disponibilidad directamente en cada sede."},
 {icon:Fish,title:"Peces y acuarios",copy:"Información orientativa sobre esta categoría, con contacto directo para confirmar la oferta disponible."},
 {icon:Bird,title:"Aves y pequeños animales",copy:"Un espacio preparado para esta categoría, sin asumir disponibilidad permanente en todas las sedes."},
];

export default function Home(){return <InteractiveShell><div className="demo-bar"><div className="container"><span>Demo privada · Propuesta conceptual de rediseño</span><a href={proposal.whatsappUrl} target="_blank" rel="noreferrer" data-event="proposal_whatsapp_click">Hablar sobre esta propuesta <ArrowRight/></a></div></div>
 <header className="header"><div className="container nav"><a className="brand" href="#inicio"><span className="brand-mark">+</span><span><b>Veterinaria</b> La Cruz</span></a><nav aria-label="Navegación principal"><a href="#atencion">Atención</a><a href="#sedes">Sedes</a><a href="#sobre">Sobre La Cruz</a><a href="#preguntas">Preguntas</a></nav><a className="button primary nav-cta" href="#sedes">Ver sedes</a></div></header>
 <main id="inicio">
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Veterinaria en Montevideo</p><h1>Cuidarlos también es estar cerca cuando lo necesitan.</h1><p className="lead">Atención veterinaria y soluciones para el cuidado de tus animales en Montevideo. Encontrá la sede que te queda mejor y comunicate directamente.</p><div className="button-row"><a className="button primary" href="#sedes"><MapPin/>Encontrar mi sede</a><button className="button outline" data-selector="call"><Phone/>Llamar ahora</button></div><p className="microcopy"><span/>Tres sedes para elegir en Montevideo</p></div><figure className="hero-image"><Image src="/images/hero-vet-care.png" alt="Escena ilustrativa de atención veterinaria a un perro y un gato; no representa al equipo real" fill priority sizes="(max-width: 900px) 100vw, 52vw"/><figcaption>Imagen ilustrativa</figcaption></figure></div></section>
  <section className="quick-section" aria-labelledby="quick-title"><div className="container"><div className="quick-head"><div><p className="eyebrow">Accesos directos</p><h2 id="quick-title">¿Qué necesitás hacer?</h2></div><p>Elegí una acción. Nosotros acortamos el camino.</p></div><div className="quick-grid"><button data-selector="call"><Phone/><span><b>Hacer una consulta</b><small>Elegir sede y llamar</small></span><ArrowRight/></button><a href="#sedes"><MapPin/><span><b>Encontrar una sede</b><small>Ver direcciones</small></span><ArrowDown/></a><button data-selector="directions"><MapPin/><span><b>Cómo llegar</b><small>Abrir indicaciones</small></span><ArrowRight/></button><a href="#atencion"><Stethoscope/><span><b>Conocer La Cruz</b><small>Atención y oferta</small></span><ArrowDown/></a></div></div></section>
  <section className="services section" id="atencion"><div className="container"><div className="section-heading"><p className="eyebrow">Atención y oferta</p><h2>Lo importante, ordenado para encontrarlo rápido.</h2><p>Estas categorías orientan la consulta. La disponibilidad concreta puede variar; para confirmarla, comunicate con la sede que prefieras.</p></div><div className="services-grid">{services.map(({icon:Icon,...s},i)=><article key={s.title} className="service-card"><div className="service-top"><Icon/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.copy}</p></article>)}</div><div className="editorial-grid"><figure><Image src="/images/consultation-owner.png" alt="Escena ilustrativa de una consulta veterinaria; no representa personas ni instalaciones reales" fill sizes="(max-width: 800px) 100vw, 58vw"/><figcaption>Imagen ilustrativa</figcaption></figure><div><p className="eyebrow">Una experiencia más directa</p><h2>De la búsqueda a una acción concreta.</h2><p>Quien llega desde Google, Maps o Instagram puede entender la propuesta, elegir una sede y comunicarse sin saltar entre plataformas.</p><a href="#sedes" className="text-link">Elegir una sede <ArrowRight/></a></div></div></div></section>
  <section className="locations section" id="sedes"><div className="container location-grid"><div className="location-copy"><p className="eyebrow light-eyebrow">Sedes</p><h2>Tres puntos de Montevideo. Elegí el que te quede más cerca.</h2><p>Direcciones y teléfonos reunidos en un solo lugar. Cada botón lleva a una acción real.</p><figure className="location-visual"><Image src="/images/location-concept.png" alt="Imagen conceptual de una fachada veterinaria; no representa ninguna sede real" fill sizes="(max-width:900px) 100vw, 38vw"/><figcaption>Imagen conceptual</figcaption></figure></div><BranchCards/></div></section>
  <section className="trust section"><div className="container trust-grid"><div><p className="eyebrow">Una presencia más clara</p><h2>Una presencia local construida durante años merece una experiencia digital igual de clara.</h2></div><div><p>Esta propuesta concentra sedes, contactos y caminos de llegada para aprovechar mejor cada visita con intención.</p><ul><li><span>01</span> Menos pasos para elegir una sede</li><li><span>02</span> Contactos separados y fáciles de actualizar</li><li><span>03</span> Estructura lista para medir conversiones</li></ul><p className="future-note">La integración de reseñas puede incorporarse cuando se validen sus datos actuales.</p></div></div></section>
  <section className="about section" id="sobre"><div className="container editorial-grid reverse"><figure><Image src="/images/reception-waiting.png" alt="Recepción veterinaria ilustrativa; no representa una sede ni personal real" fill sizes="(max-width:800px) 100vw, 52vw"/><figcaption>Imagen ilustrativa</figcaption></figure><div><p className="eyebrow">Sobre La Cruz</p><h2>Cuidado cotidiano y atención veterinaria, más cerca.</h2><p>La Cruz combina atención veterinaria con una oferta orientada al cuidado cotidiano de animales y presencia en distintos puntos de Montevideo.</p><p>Esta demo propone reunir esa información en una experiencia simple, especialmente pensada para quienes buscan desde el celular.</p></div></div></section>
  <section className="faq section" id="preguntas"><div className="container faq-grid"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Lo operativo, sin vueltas.</h2><p>Respuestas simples para decidir el próximo paso.</p></div><div>{[
   ["¿Cómo me comunico con una sede?","Podés elegir Unión, Curva o Carrasco y llamar directamente desde esta página."],
   ["¿Dónde están ubicados?",`Unión: ${branches[0].shortAddress}. Curva: ${branches[1].shortAddress}. Carrasco: ${branches[2].shortAddress}.`],
   ["¿Cómo obtengo indicaciones para llegar?","Usá “Cómo llegar” en la sede que prefieras. Se abrirá una búsqueda de Google Maps con la dirección correspondiente."],
   ["¿Dónde consulto la disponibilidad de un producto o atención?","Lo más directo es llamar a la sede que prefieras para consultar la disponibilidad actual."],
  ].map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></div></section>
  <section className="proposal section"><div className="container proposal-inner"><div><p className="eyebrow light-eyebrow">Sobre esta propuesta</p><h2>Esta demo puede convertirse en la nueva web de La Cruz.</h2><p>La versión final puede adaptarse a la identidad definitiva, fotografías reales, servicios, contactos y horarios confirmados. También puede crecer hacia catálogo o tienda, analítica y futuras funcionalidades.</p></div><div className="proposal-actions"><a className="button warm" href={proposal.whatsappUrl} target="_blank" rel="noreferrer" data-event="proposal_whatsapp_click">Quiero hablar sobre esta propuesta <ArrowRight/></a><span>WhatsApp del creador · {proposal.whatsappDisplay}</span><a className="button line-light" href={proposal.emailUrl} data-event="proposal_email_click"><Mail/>Enviar un correo</a></div><p className="proposal-note">Esta sección pertenece únicamente a la presentación comercial y no formaría parte de la experiencia pública final salvo que el cliente lo desee.</p></div></section>
 </main>
 <footer><div className="container footer-grid"><div><a className="brand footer-brand" href="#inicio"><span className="brand-mark">+</span><span><b>Veterinaria</b> La Cruz</span></a><p>Montevideo, Uruguay</p></div><div className="footer-branches">{branches.map(b=><div key={b.id}><b>{b.name}</b><span>{b.shortAddress}</span><a href={b.phoneHref}>{b.phoneDisplay}</a></div>)}</div></div><div className="container legal">Demo conceptual privada · no constituye el sitio oficial de Veterinaria La Cruz.<span>Imágenes ilustrativas.</span></div></footer>
 </InteractiveShell>}
